export const ADD = 'ADD'
export const SUBTRACT = 'SUBTRACT'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD_RESULT = 'ADD_RESULT'
export const DELETE_RESULT = 'DELETE_RESULT'